functionsDirectory = "/Users/christophercarvalho/uys-js/Users/christophercarvalho/uys-js/netlify/functions"
functionsDirectoryOrigin = "ui"
headers = []
redirects = []

[functions]

[functions."*"]

[[plugins]]
package = "@netlify/plugin-nextjs"
origin = "ui"

[plugins.inputs]

[build]
publish = "/Users/christophercarvalho/uys-js/out"
publishOrigin = "ui"
command = "next build"
commandOrigin = "ui"
functions = "/Users/christophercarvalho/uys-js/Users/christophercarvalho/uys-js/netlify/functions"

[build.environment]
NEXT_PRIVATE_TARGET = "server"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]